name: Trivy Secret Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  trivy-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan for secrets with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: secret
          format: table
          exit-code: 0  # Altere para 1 se quiser falhar o pipeline